name: LaTeX to PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: dante-ev/ghactions-texlive@v1
      with:
        packages: full

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode your-document.tex
        # Replace 'your-document.tex' with the name of your main .tex file

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: your-document.pdf
