name: LaTeX to PDF

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      uses: zauguin/install-texlive@v3
      with:
        packages: >
          latexmk
          l3build
          latex
          latex-bin
          luatex
          latex-bin-dev
          collection-amslatex  # Include the AMS LaTeX collection
          # Add any additional packages you need here

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode your-document.tex
        # Replace 'your-document.tex' with the name of your main .tex file

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: your-document.pdf
        # Replace 'your-document.pdf' with the name of the output PDF
